# Generated by Django 3.0 on 2020-04-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20200429_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
