# Generated by Django 3.0 on 2020-04-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200429_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='policy',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='Номер страхового полиса'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='snils',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='СНИЛС'),
        ),
    ]
